### ISSUE TITLE
Quiero hablar contigo

### ISSUE THREAD

**Issue by IvanMolina99** [jmcbg01/eclipse_proyectos#2]
Permiteme hablar contigo una vez.
Me da igual si es por teléfono, whatsapp o telegram

No soy mala persona y quiero arreglarlo, yo no tenia mala intención para hablarte

Por favor josemi, dame la oportunidad de hablar contigo

**Comment by IvanMolina99** [comment]
Prometo ser bueno a partir de ahora, no era consciente de que te hacía daño.

Si hubiera sido consciente, no lo habría hecho. Creeme

**Comment by IvanMolina99** [comment]
Lo se, me pediste que no te hablara por nada, pero en mi estúpida cabeza pensé que te haría feliz un libro

La intención no era mala, es por eso que quiero arreglarlo
Yo solo quería animarte, creeme

**Comment by IvanMolina99** [comment]
Quiero disculparme por todo, por haberte hecho dibujos que no querías, por haberte hecho regalos que no quieres y por haberte hablado y siento muchísimo también no haberte dejado aquella semana tranquilo para que estudiaras para tu examen.

Siento haberte hecho daño, estoy muy arrepentido
Estoy siendo sincero, quiero arreglarlo

**Comment by IvanMolina99** [comment]
Jamás me perdone que suspendieras del examen de conducir por mi culpa, siento que aquello pasara

Se que fue lo que mas daño te ha hecho, y siento no poder cambiar lo que ya pasó

**Comment by jmcbg01** [comment]
1. Te lo he perdonado todo 1000 veces

2. Si lo quieres arreglar por qué me sigues hablando?


Es que no lo entiendo. Me dices que te perdone por hablarte, pero le sigues hablando. 

3. Insisto, estas perdonado. Pero deja de hablarme

**Comment by IvanMolina99** [comment]
Vale, dejo de hablarte.
Gracias por perdonarme

Espero que te pongas bien para poder arreglarlo algún día

**Comment by IvanMolina99** [comment]
> 1. Te lo he perdonado todo 1000 veces
> 2. Si lo quieres arreglar por qué me sigues hablando?
> 
> Es que no lo entiendo. Me dices que te perdone por hablarte, pero le sigues hablando.
> 
> 1. Insisto, estas perdonado. Pero deja de hablarme

Solo dime una cosa, si dejo de hablarte como te prometí, de verdad volverás a hablarme?

No entiendo el mensaje josemi

**Comment by IvanMolina99** [comment]
> 1. Te lo he perdonado todo 1000 veces
> 2. Si lo quieres arreglar por qué me sigues hablando?
> 
> Es que no lo entiendo. Me dices que te perdone por hablarte, pero le sigues hablando.
> 
> 1. Insisto, estas perdonado. Pero deja de hablarme

Solo dime una cosa, si dejo de hablarte como te prometí, de verdad volverás a hablarme?

No entiendo el mensaje josemi, cuando dices que no te hable es mientras te pones bien o es para siempre? :(

Solo quiero que todo sea como antes de hablarte ayer

**Comment by IvanMolina99** [comment]
![IMG_20210426_155051_836](https://user-images.githubusercontent.com/17816606/116093753-3abac500-a6a7-11eb-8f91-e8a90406532a.jpg)

Porqué me dices eso a través de otra persona.
Sabes que me haces mucho daño diciéndome eso
